### ISSUE TITLE
Not possible to create booking

### ISSUE THREAD

**Issue by robertengelmann** [DSD-BookEasy/BookEasy#13]
Bad Request (#400), when hitting "Confirm" on a booking creation (I was logged in as admin).

**Comment by BaggioAlessandro** [comment]
Did you try to book a timeslot outside opening hours or during opening hours? Booking during opening hours should work fine

**Comment by robertengelmann** [comment]
Outside the opening hours. Sebastian just told me that Stefano already has a fix for this, but couldn't push it to dev, yet.
