### ISSUE TITLE
create-weekdays price calculation

### ISSUE THREAD

**Issue by robertengelmann** [DSD-BookEasy/BookEasy#18]
The price calculation only shows the fixed value for one slot in the simulator. I would like to have something like this in one line:
Simulator price: 200$ per 30 minutes
But I can only produce:
Simulator price per slot: 200$
Slot duration: 30 minutes

It would also be nice to actually calculate the price, already but it's enough if this is done on the final page, as long as the customer is informed about the slot duration, so he can make a calculation himself.
However this is not so important.

**Comment by ske14002** [comment]
Should be done for create-weekdays for now
