### ISSUE TITLE
Delete staff member

### ISSUE THREAD

**Issue by robertengelmann** [DSD-BookEasy/BookEasy#20]
When I try to delete a staff member by clicking on the trash bin or on the red delete button in his view I get the following error:
Unable to resolve the request: staff/delete 

I was logged in as admin

**Comment by BaggioAlessandro** [comment]
I see that action delete is missing. This is the reason of the bug. There is someone that is working on it or I can add it?

**Comment by paolomanca** [comment]
I will do it, together with the create.

**Comment by robertengelmann** [comment]
I think that was working now. Thank you.

**Comment by ste-camp** [comment]
This is actually not done. There is no code for staff deletion

**Comment by paolomanca** [comment]
Since we don't want to lose information (i.e. who was the instructor for a timeslot), instead of deletion I've implemented disabling. See commit a02fd35 and others
