### ISSUE TITLE
'Repeat password' validating if empty

### ISSUE THREAD

**Issue by paolomanca** [DSD-BookEasy/BookEasy#21]
In 'Create Staff' page, the field repeat password doesn't return error if it's left empty when the password field it's not.

**Comment by robertengelmann** [comment]
That's because I didn't know how to put a conditional statement in this place. The repeat password can't be always required, otherwise it would not be possible to change account information without entering a new password.

**Comment by paolomanca** [comment]
The default value (true) for the property 'skipOnEmpty' was the cause of this issue.
