### ISSUE TITLE
Deleting an existing booking removes time slot

### ISSUE THREAD

**Issue by ske14002** [DSD-BookEasy/BookEasy#24]
When I delete an existing booking, the linked time slot gets deleted as well. Is this the desired behaviour?

**Comment by robertengelmann** [comment]
No it's not desired. We always want to keep all information, especially our recurring time slots :P
I will look into this, if no one is faster.

**Comment by BaggioAlessandro** [comment]
Actually I think that on weekdays booking the time slots are deleted. With opening hours booking I think  we just release timeslots since they are no longer unavailable

**Comment by BaggioAlessandro** [comment]
Check the handleDeleteBooking() in TimeSlot, it is called when a booking is deleted

**Comment by robertengelmann** [comment]
I just tried it again, and the time slot remained on Sunday. I will do more testing to see if this is solved.
