### ISSUE TITLE
Move 'Pick a Date'

### ISSUE THREAD

**Issue by ske14002** [DSD-BookEasy/BookEasy#27]
Move 'Pick a Date' above the calendar since it does not look good on mobile devices.

**Comment by ske14002** [comment]
I tried working on but can't make it work

**Comment by mertergun** [comment]
I may have a look at this tomorrow night

**Comment by robertengelmann** [comment]
Sebastian and I also tried to "just put it in the same row as the buttons" and I accidentilly commited it... well, at least you can see now what happens: The datepicker expands always, which looks quite stupid.

**Comment by mertergun** [comment]
I did a workaround, CSS codes are in the attributes, I can make it prettier if you agree it is okay

**Comment by ske14002** [comment]
Is this related to the changes of the date picker?

![screen shot 2015-01-08 at 12 27 29 pm](https://cloud.githubusercontent.com/assets/9962237/5661909/bd806828-9731-11e4-8837-86456cf5cc74.png)

**Comment by mertergun** [comment]
probably yes let me check

**Comment by mertergun** [comment]
It figured out that is related to the width of the calendar and the aspect ratio defined in the widget. It is fixed now. I put most of the css attributes to site.css and applied this to staff view, too
