### ISSUE TITLE
Deleting a Time Slot Model

### ISSUE THREAD

**Issue by ske14002** [DSD-BookEasy/BookEasy#29]
What happens to a booking if we delete the linked Time Slot Model? What is currently implemented? Thijmen suggested some kind of warning but I would rather like to delete the Time Slot but keep the Booking.

What do you think?

**Comment by paolomanca** [comment]
Look the phpdoc/code of controllers/TimeslotModel::deleteTimeslots. The behaviour is to keep booked timeslots, but there is support (not currently used) for forced removal.

**Comment by robertengelmann** [comment]
I just tried this and the behaviour is as described by @paolomanca 
I think this is conform with our customer. I will answer his question in time and see if he has other feedback.
