### ISSUE TITLE
Secret key when booking as logged in

### ISSUE THREAD

**Issue by robertengelmann** [DSD-BookEasy/BookEasy#36]
When I am logged in, I don't get to see the secret key of a booking, which is not good, if I do a booking for someone over telephone (or similar).
Anyway, why are there two different views for staff and customer, isn't it easier to merge them and make the condition for the buttons inside one view?

**Comment by BaggioAlessandro** [comment]
I thought to keep them separetly because they show different content. I din't want to put too many if statement in the view to check all the time what to show for a login or anonimous user.

**Comment by BaggioAlessandro** [comment]
Secret key should be visible now
