### ISSUE TITLE
No error handling in BookingController

### ISSUE THREAD

**Issue by ste-camp** [DSD-BookEasy/BookEasy#44]
All the exceptions and errors in Booking Controller are left empty without any explanation, especially in actionConfirm()

There should at least be basic error messages

**Comment by BaggioAlessandro** [comment]
should be fine now. Let me know if the way I used for the error message doesn't work with your way of extracting string for trasnlation

**Comment by ste-camp** [comment]
Mmh, no it doesn't work.
But the main problem is that generic messages such as "Invalid Input" are useless because the system already prints something like that by himself. You should put specific errors about what happened in the page.
I have fixed them now.
